name: Backend Test
on: 
  push:
      branches: [main]
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-22.04
    defaults:
      run: 
        working-directory: backend
        
    steps:
      - name: setup
        uses: actions/checkout@v4
      - name: node setup
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: install dependencies
        run: npm ci
      - name: Run All tests
        run: npm run test
